### ISSUE TITLE
Keeping track of all tags for a global search

### ISSUE THREAD

**Issue by lmburns** [vv9k/wutag#29]
## Feature Request
I'm on macOS and I also use [this](https://github.com/jdberry/tag) program which is another tagging tool. It has quite a few features and I understand that your version is compatible with more than just macOS, so not all features would necessarily be compatible; however, here is my request:

Add support to somehow keep track of all the tags that are set. For instance a file could be placed in `${XDG_DATA_HOME:-$HOME/.local/share}/wutag` that could be some sort of database, or just some plain text file that would allow for the user to list all their tagged files. Perhaps the option to sort by tag and or directory as well (in this global feature).  This feature is similar to the `--home` or `--local` option in the program I linked above.

Edit: 
I might also add that it would help to have this feature because when using the closes thing to it (`wutag -d ~ list '**'`), I get several errors on some files. For example:
```
ERROR error: Permission denied (os error 13)
ERROR provided file doesn't exists
```
It would be helpful if I could clear these with `clear` or know which files these are referring to.

**Comment by wojciechkepka** [comment]
I thought about storing some sort of state briefly so I opened #6 and indeed I think this would greatly increase user experience. I think storing the state in OSs cache dir would be better, I would prefer to keep out of users home directory. 

I will also put some work into the error messages. It should at least state what file the error refers to.
