### ISSUE TITLE
Make actions and output scriptable first

### ISSUE THREAD

**Issue by HumanG33k** [vv9k/wutag#33]
Hello,

I want to tag a specify directory or file. 
For file should i specify -m 1 in order to prevent to go in subdir ? 
 
I think it's because of -d option but we can not use a fullpath to add a file ? 

Maybe i have issues/miss with something.

**Comment by vv9k** [comment]
Hi,

That is correct, To tag a single file or a directory you have to do `wutag -m 1 set filename <tags>...`.

And if you want to do this in other directory you have to add `-d` or change the shell's directory with `cd` before executing `wutag`.

Example:
```

~ ❯ ls -l ~/dev/ | grep rust
drwxr-xr-x  - user 26 Jul 07:43 rust

~ ❯ wutag -d ~/dev -m 1 set rust code
/home/user/dev/rust:
        + code
```
Or like this:
```
~ ❯ cd ~/dev/

~/dev ❯ wutag -m 1 set rust code2
/home/user/dev/rust:
        + code2

```

This looks like something that should be improved, perhaps a flag that will make wutag treat the pattern as a path to the file would work.

**Comment by HumanG33k** [comment]
Thx for the feedback.
Mainly my use cases are : 
- pattern tag. Like in documentation)
- directory tag. Use as semantic information for my workflow : (Status : Alpha, Beta [...], Mature) (State : Working, Pause, etc)(Project : Personnal, Profesionnal)
- file tag. for notes and todo


I have some good application for tags : 
With file/dir watcher auto-tag. 
Software can also use as in/out action filter.
For ie : 
- a dir Pictures with a file watcher
- autotag photo if .jpg || .png
- one by day an opencv run on photo tags with AI and auto add tags cats || dog  


Wutag should be design scriptable. As ip vs ifconfig.
