### ISSUE TITLE
Are the tags automatically recognized by dolphin and other programs that use xattr?

### ISSUE THREAD

**Issue by JediMaster25** [vv9k/wutag#35]
I want to add a list of tags to a file programmatically but I don't know how to do that using Dolphin. I was looking around and I've seen that this program uses the same way of keeping track of the tags, but I'm not sure how xattr works, so I don't know if I add tags with wutag to a file will I be able to search for those files using the tags in Dolphin or only with wutag?

**Comment by vv9k** [comment]
Tags are currently stored in a way that makes them unique to wutag. They might get picked up by other programs, but they won't look the same. The reason why is that tags get serialized in cbor and prefixed with `wutag.` for easier future extraction as can be seen here: https://github.com/vv9k/wutag/blob/6d697957cc87ad75c380b6cd7f7ecaee2ef83182/wutag_core/tag.rs#L99-L102

It might be worth revisiting if there are usecases for the tags to be plaintext.

**Comment by JediMaster25** [comment]
Could you give an example of how would I serialize the tags in cbor and prefix them with wutag. I think it would be something like:

```
import cbor2
USERSPACE = "user.wutag"
def import_to_wutag(path: str, tags: List[str]) -> None:
    serialized_tags = cbor2.dumps(tags)
    write_xattr(path, serialized_tags)
    xattr.setxattr(path, USERSPACE, serialized_tags)
```
