### ISSUE TITLE
When I provide a list of tags sometimes I get OSError: [Errno 28] No space left on device. Make the error more informative

### ISSUE THREAD

**Issue by JediMaster25** [vv9k/wutag#37]
When I give a list of tags instead of giving many errors it should give only one. And it should say something like `xattributes limit reached` instead of `[OSError: [Errno 28] No space left on device` which makes it seem as if you've run out of storage space in the hard drive.

**Comment by vv9k** [comment]
Thanks for this report. I added some better handling in c151ea44aeee00db63c98f29ffa87625bf661fa0 . Local tests show promising results. Seems like the limit on Linux is 50 xattrs.

```
❯ cargo r --  set 'README*' test
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
     Running `target/debug/wutag set 'README*' test test2`
/home/wojtek/dev/rust/wutag/README.md:
        ERROR xattributes limit reached on the file - `No space left on device (os error 28)`
```
