### ISSUE TITLE
Tagging not working

### ISSUE THREAD

**Issue by JediMaster25** [vv9k/wutag#40]
Manjaro Linux, wutag 0.5.0-dev

```
❯ rm -rf test
❯ touch test
❯ wutag set test "tag1" "tag2"
error: The following required arguments were not provided:
    <TAGS>...

USAGE:
    wutag set <PATHS>... <TAGS>...

For more information try --help
```

**Comment by vv9k** [comment]
I think your version might be using older `clap` that displayed the help message wrong.

You'd have to do:
```
wutag set test -- "tag1" "tag2"
```
Notice the double hyphen `--` before tags.

This is no longer the case if you'd use version 0.5.0 or master branch as it got changed in 602d3e6a0726be9ee38cf6a94784588e462cfd28 to accept tags with `--tags` flag. 

The new usage looks like this:
```
Usage: wutag set [OPTIONS] --tags [<TAGS>...] [PATHS]...
```
So if you update to the newest version you'd have to do:
```
wutag set test --tags "tag1" "tag2"

#or

wutag set test -t "tag1" "tag2"
```

The

**Comment by JediMaster25** [comment]
That's weird because I have the [wutag-git](https://aur.archlinux.org/packages/wutag-git) installed in arch. I'll uninstall and reinstall to see if I get the last version.

**Comment by vv9k** [comment]
Try installing the `wutag` package as it's the most recent. I completely forgot to update the `-git` package, will take care of it now.
